// <auto-generated />
namespace OauthIdentityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_db_to_sqlserver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_db_to_sqlserver));
        
        string IMigrationMetadata.Id
        {
            get { return "201809060155322_update_db_to_sqlserver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
